FROM ubuntu:trusty

RUN apt-get update && apt-get -y upgrade && \
	apt-get -y install git && \
	apt-get -y install wget && \
	apt-get -y install ca-certificates &&\
	apt-get -y install openssh-server && \
	apt-get -y install apt-transport-https && \
	apt-get -y install curl && \
	apt-get -y install gnupg